services:
  mc-server:
    image: itzg/minecraft-server:latest
    volumes:
      - ./data:/data:rw

    ports:
      - 10000:25565
    environment:
      MEMORY: "4G"
      EULA: "TRUE"
      TYPE: "FABRIC"
      ONLINE_MODE: "FALSE"
      MOTD: "Skyworks 1.18 Vanilla Minecraft Server"

    stdin_open: true
    tty: true

    restart: unless-stopped
