services:
  mc-server:
    image: itzg/minecraft-server:latest
    volumes:
      - ./data:/data:rw

    ports:
      - 10000:25565
    environment:
      MEMORY: "6G"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.18.2"
      ONLINE_MODE: "FALSE"
      MOTD: "Skyworks [Open] 1.18 Modded Minecraft Server"

    stdin_open: true
    tty: true

    restart: unless-stopped
