services:
  mc-server:
    image: itzg/minecraft-server:latest
    volumes:
      - ./data:/data:rw

    ports:
      - 20000:25565
    environment:
      MEMORY: "8G"
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.18.1"
      ONLINE_MODE: "FALSE"
      MOTD: "Skyworks 1.18 Modded Minecraft Server"

      USE_AIKAR_FLAGS: "true"

    stdin_open: true
    tty: true

    restart: unless-stopped
